### ISSUE TITLE
FileNotFoundError with absolute path

### ISSUE THREAD

**Issue by elisagdelope** [KalyanMurapaka45/DocGenius-Revolutionizing-PDFs-with-AI#2]
I cloned the repo and tried to run it locally, however after `streamlit run app.py` I got: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KALYAN\\Desktop\\Projects\\DocGenius\\images.jpeg'.

It seems like it's looking for an absolute path. Perhaps this is an easy fix with a relative path instead.

**Comment by KalyanM45** [comment]
As I mentioned, replace my absolute path or use a relative path. However, the images.jpeg file is there
